# dataset:
data_dir: "/mnt/nlp/zhiyang.zzy/project/python3project/data_warehouse_code/data/out/"
train_file: "train.20200630.seg"
test_file: "test.20200630.seg"
dev_file: "val.20200630.seg"
mini_file: "train.mini"
predict_file: "./result/osnlu/train.mini"

meta_dir : "./data/osnlu/"
intent_file: "actions.txt"
tag_file: "tags.txt"
max_seq_len: 35
unk_word: "$UNK$"
pad_word: "$PAD$"
unk_tag: "O"
batch_size: 512
bert_dir: &bert_dir '/Volumes/HddData/ProjectData/NLP/bert/chinese_L-12_H-768_A-12/'
# bert_dir: "/mnt/nlp/bert/ERNIE_stable-1.0.1/checkpoints/"
bert_init_checkpoint: "bert_model.ckpt"
bert_vocab: "vocab.txt"
bert_config: "bert_config.json"

# model:
alias: "meta_nlu"
task_type: "train"
# checkpoint_dir: "result/checkpoint/bert_1019/model" # 非crf，
# checkpoint_dir: "result/checkpoint/bert_1019_crf/model" # crf，
checkpoint_dir: "result/checkpoint/bert_1023_crf/model" # crf，使用train.20200630|数据训练，不带外卖
saved_model_dir: "result/pbmodel/bert_1019/"
early_stop: True
epoch_no_imprv: 5
use_crf: 1
optimizer: "adam"
learning_rate: 0.001
lr_decay: 0.95
decay_step: 7000
dropout: 0.3
num_epoch: 30
embedding_dim: 100
bert_lr: 0.00005
warmup_proportion: 0.1
use_sigmoid: 1